### ISSUE TITLE
Not working on Ubuntu 25.10/ansible 2.19.0

### ISSUE THREAD

**Issue by acaskey-demaret-nshift** [theko2fi/ansible-multipass-collection#21]
After a fresh install of Ubuntu 25.10, the collection does not seem to work.

During install I get:

`[WARNING]: Collection cloud.common does not support Ansible version 2.19.0`

Multipass VMs are created successfully with: `theko2fi.multipass.multipass_vm`

But then attempts to gather facts from the vms results in:

```
TASK [Gathering Facts] ****************************************************************************************************************************************************************************************************************
[ERROR]: Task failed: cannot import name 'selectors' from 'ansible.module_utils.compat' (/usr/lib/python3/dist-packages/ansible/module_utils/compat/__init__.py)
fatal: [test1]: FAILED! => {"changed": false, "msg": "Task failed: cannot import name 'selectors' from 'ansible.module_utils.compat' (/usr/lib/python3/dist-packages/ansible/module_utils/compat/__init__.py)"}
fatal: [test2]: FAILED! => {"changed": false, "msg": "Task failed: cannot import name 'selectors' from 'ansible.module_utils.compat' (/usr/lib/python3/dist-packages/ansible/module_utils/compat/__init__.py)"}
```

**Comment by realishtv** [comment]
See #22 

You can use this immediately by editing your requirements.yml:

```yaml
  - name: theko2fi.multipass
    type: git
    source: https://github.com/realishtv/ansible-multipass-collection.git
```
Reinstall with --force: `ansible-galaxy install -r requirements.yml --force`
